version: "3.8"
services:
  db:
    image: "postgres:14.1-alpine" 
    restart: always
    container_name: "doc-pgsql-container"  
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=doc-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    image: "devops-assignment:latest"
    build:
      context: ./
    container_name: "doc-assignment-container"  
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/doc-db
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.jba.hibernate.ddl-auto=update

volumes:
  db:
    driver: local
