name: CI Pipeline (DOC1)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build, Test and Dockerize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Unit Tests
        run: ./mvnw test

      - name: Build Application
        run: ./mvnw package -DskipTests

      - name: Build Docker Image
        run: docker build -t viatabdoc-app .
